---
- name: Include platform-specific tasks
  include_tasks: "{{ provision_type }}.yml"

- name: Include distro-specific tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: Update all packages
  yum:
    name: "*"
    state: latest
  retries: 3  # This seems to fail sometimes, so lets retry before failing everything
  until: update_all_packages.rc == 0
  register: update_all_packages
  become: yes

- block:
    - name: Reboot host
      shell: sleep 30 && shutdown -r now
      async: 30
      poll: 0
      ignore_errors: yes
      become: yes

    - name: Wait for nodes to reboot
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
  when: "'kernel' in update_all_packages.results"

- name: Install preferred packages
  yum:
    name:
      - vim-enhanced
      - screen
    state: present
  become: yes
