---
- name: Check to see if system is already registered to RHSM
  command: subscription-manager status
  register: sub_status
  ignore_errors: true

- name: Register host to RHSM and attach pool
  redhat_subscription:
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
    pool_ids: "{{ rhsm_pool }}"
    consumer_name: "{{ rhsm_consumer_name | default(omit) }}"
    state: present
  become: yes
  when: sub_status.rc == 1

- name: Disable repos for pool ID - useful for Employee SKUS
  rhsm_repository:
    name: '*'
    state: disabled
  retries: 3
  become: yes

- name: Enable required repositories
  rhsm_repository:
    name: "{{ openshift_repos }}"
    state: enabled
  retries: 3  # This seems to fail sometimes, so lets retry before failing everything
  register: openshift_enable_repos
  become: yes
