---
- hosts: tag_openshift_cluster_name_{{ cluster_group_name }}
  any_errors_fatal: yes
  roles:
    - host_prep_general

- hosts: tag_openshift_nodes:&tag_openshift_cluster_name_{{ cluster_group_name }}
  any_errors_fatal: yes
  roles:
    - host_prep_openshift

- hosts: tag_openshift_role_bastion:&tag_openshift_cluster_name_{{ cluster_group_name }}
  any_errors_fatal: yes
  roles:
    - host_prep_bastion
    - install_openshift

- hosts: tag_openshift_role_master:&tag_openshift_cluster_name_{{ cluster_group_name }}
  roles:
    - create_users
