---
- hosts: openshift_cluster_openshift_redhatgov_io
  any_errors_fatal: yes
  roles:
    - rhsm_subscribe
    - host_prep_general

- hosts: openshift_nodes:&openshift_cluster_openshift_redhatgov_io
  any_errors_fatal: yes
  roles:
    - host_prep_openshift

- hosts: openshift_role_bastion:&openshift_cluster_openshift_redhatgov_io
  any_errors_fatal: yes
  roles:
    - host_prep_bastion
    - install_openshift

- hosts: openshift_role_master:&openshift_cluster_openshift_redhatgov_io
  roles:
    - create_users
