---

- hosts: localhost
  roles:
    - provision_rhv

- hosts: openshift_cluster_{{ hostvars.localhost.cluster_group_name }}
  any_errors_fatal: yes
  roles:
    - rhsm_subscribe
    - host_prep_general

- hosts: openshift_nodes:&openshift_cluster_{{ hostvars.localhost.cluster_group_name }}
  any_errors_fatal: yes
  roles:
    - host_prep_openshift

- hosts: openshift_role_bastion:&openshift_cluster_{{ hostvars.localhost.cluster_group_name }}
  any_errors_fatal: yes
  roles:
    - host_prep_bastion
    - install_openshift

- hosts: openshift_role_master:&openshift_cluster_{{ hostvars.localhost.cluster_group_name }}
  roles:
    - create_users
